# Generated by Django 5.0.2 on 2024-03-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60, verbose_name='Статус бронирования')),
                ('start', models.CharField(max_length=60, verbose_name='Начало бронирования')),
                ('end', models.CharField(max_length=60, verbose_name='Конец бронирования')),
                ('duration', models.CharField(max_length=60, verbose_name='Продолжительность')),
                ('price', models.CharField(max_length=60, verbose_name='Стоимость заказа')),
                ('source', models.CharField(max_length=60, verbose_name='Источник бронирования')),
                ('phone', models.CharField(max_length=60, verbose_name='Телефон клиента')),
                ('email', models.CharField(max_length=60)),
                ('ful_name', models.CharField(max_length=60, verbose_name='Полное имя')),
                ('comment', models.CharField(max_length=60, verbose_name='Комментарий к заказу')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text='Время получения веб-хука.')),
                ('payload', models.JSONField(default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['received_at'], name='webhooks_we_receive_b5d6c2_idx')],
            },
        ),
    ]
