# Generated by Django 5.0.2 on 2024-03-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_alter_customer_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='comment',
            field=models.CharField(max_length=60, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='duration',
            field=models.CharField(max_length=60, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=60, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(max_length=60, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(max_length=60, verbose_name='Статус'),
        ),
    ]
