# Generated by Django 5.0.2 on 2024-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_customer_tag_alter_customer_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bed_sheet',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Простыня'),
        ),
        migrations.AddField(
            model_name='customer',
            name='birch_broom',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Веник бер.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='oak_broom',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Веник дуб'),
        ),
        migrations.AddField(
            model_name='customer',
            name='people_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во чел.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='prepayment',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Предоплата'),
        ),
        migrations.AddField(
            model_name='customer',
            name='robe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Халат'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rotenburo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ротэнбуро'),
        ),
        migrations.AddField(
            model_name='customer',
            name='slippers',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Тапки'),
        ),
        migrations.AddField(
            model_name='customer',
            name='towel',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Полотенце'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Примечание'),
        ),
    ]
