# Generated by Django 5.0.2 on 2024-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_customer_bed_sheet_customer_birch_broom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='end',
            field=models.CharField(max_length=60, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start',
            field=models.CharField(max_length=60, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание'),
        ),
    ]
