# Generated by Django 5.0.2 on 2024-03-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_rename_customer_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='amount',
            field=models.CharField(max_length=50, null=True, verbose_name='Внесено'),
        ),
    ]
