# Generated by Django 5.0.2 on 2024-03-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0008_guest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rotenburo',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ротэнбуро'),
        ),
    ]
