# Generated by Django 5.0.2 on 2024-03-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0009_alter_guest_rotenburo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='uid',
            field=models.CharField(max_length=256, null=True, verbose_name='booking_uuid'),
        ),
    ]
