# Generated by Django 5.0.2 on 2024-04-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0010_guest_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='price_formatted',
            field=models.CharField(max_length=60, null=True, verbose_name='Стоимость заказа'),
        ),
    ]
