# Generated by Django 5.0.2 on 2024-04-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0011_guest_price_formatted'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='rotenburo_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ротенбуро_1'),
        ),
    ]
