# Generated by Django 5.0.2 on 2024-04-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0012_guest_rotenburo_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Резерв')),
                ('base_sauna_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена бани')),
                ('rotenburo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ротэнбуро')),
                ('birch_broom', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Веник бер.')),
                ('oak_broom', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Веник дуб')),
                ('bed_sheet', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Простыня')),
                ('towel', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Полотенце')),
                ('robe', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Халат')),
                ('slippers', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Тапки')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='webhooks.guest')),
            ],
        ),
    ]
