# Generated by Django 5.0.2 on 2024-03-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, max_length=20)),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон')),
                ('full_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('date', models.CharField(max_length=20, verbose_name='Дата')),
                ('email', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=20, verbose_name='Источник бронирования')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('booking_id', 'phone'), name='unique_phone_booking_id'),
        ),
    ]
