# Generated by Django 5.0.2 on 2024-03-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnovo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_phone_booking_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='booking_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
