# Generated by Django 5.0.2 on 2024-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnovo', '0002_remove_customer_unique_phone_booking_id_customer_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
