# Generated by Django 5.0.2 on 2024-03-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnovo', '0004_alter_customer_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
