# Generated by Django 5.0.2 on 2024-03-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnovo', '0006_customer_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='real_arrival',
            field=models.CharField(default='', max_length=40, verbose_name='Время заезда'),
        ),
        migrations.AddField(
            model_name='customer',
            name='real_departure',
            field=models.CharField(default='', max_length=40, verbose_name='Время выезда'),
        ),
        migrations.AddField(
            model_name='customer',
            name='room_id',
            field=models.CharField(default='', max_length=40, verbose_name='Номер Домика'),
        ),
    ]
