# Generated by Django 5.0.2 on 2024-03-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnovo', '0008_alter_customer_real_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adults',
            field=models.CharField(default='2', max_length=20, verbose_name='Взрослых'),
            preserve_default=False,
        ),
    ]
