# Generated by Django 5.0.2 on 2024-03-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnovo', '0009_customer_adults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='room_id',
            field=models.CharField(max_length=40, null=True, verbose_name='Номер Домика'),
        ),
    ]
