# Generated by Django 5.0.2 on 2024-03-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnovo', '0010_alter_customer_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.CharField(max_length=50, null=True, verbose_name='Проживание'),
        ),
        migrations.AddField(
            model_name='customer',
            name='children',
            field=models.CharField(max_length=20, null=True, verbose_name='Детей'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_early_arrival',
            field=models.CharField(max_length=256, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_late_departure',
            field=models.CharField(max_length=256, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='need_online_payment',
            field=models.CharField(max_length=256, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='service_total',
            field=models.CharField(max_length=256, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='status_name',
            field=models.CharField(max_length=256, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='adults',
            field=models.CharField(max_length=20, null=True, verbose_name='Взрослых'),
        ),
    ]
